### ISSUE TITLE
Korean character support

### ISSUE THREAD

**Issue by DagoDagorath** [matigramirez/Parsec#22]
Various files (most notably *.eft) in clients are often using Korean characters as description or in this case as Scene names. Can be sometimes useful to understand what is being said in order to comprehend file structure better or what the original developers intended/commented.
Using guildanteroom.eft as example
[guildanteroom.zip](https://github.com/matigramirez/Parsec/files/7651612/guildanteroom.zip)
When converted to json from eft the characters are converted to ???
```cs
 "signature": "EFT",
    "file3DECount": 2,
    "file3DENames": ["potal001.3DE", "invertical019.3DE"],
    "fileDDSCount": 10,
    "fileDDSNames": ["lamp003.dds", "fire003.dds", "fire_010000.dds", "v20.dds", "fire004.dds", "waveRt00.dds", "twistRing02.dds", "Ofire00.dds", "Ofire01.dds", "Ofire02.dds"],
    "sceneCount": 12,
    "scenes": [{
            "name": "????????02",
            "unknown01": 0,
            "unknown02": 0,
            "unknown03": 0,
```
And when converting back into *.eft the information is saved back with ???

(Left - generated *.eft from *.json, Right - original *.eft)
![image](https://user-images.githubusercontent.com/39481492/144653699-a73bf641-9cba-439d-845e-65cd3c45db36.png)

Castor displayed them as:

![image](https://user-images.githubusercontent.com/39481492/144654081-303db9f5-4762-4f78-bc5b-e63ed37539dd.png)

Which means "torch light source" when translated.

**Comment by matigramirez** [comment]
After some research I found that those Korean characters use UTF-16 encoding but numbers use UTF-8 encoding. Not only that but also there's some files that use UTF-8 entirely (see Monster.EFT). 
Text editors can't open text files with multiple encodings at the same time (not that I know of) and since object (.3DE) and texture (.DDS) names are UTF-8 encoded, there isn't much I can do about this inconsistency. All things considered, this issue is out of the scope of Parsec.
With that said, feedback is always appreciated and I'm glad you brought this to my attention.
