### ISSUE TITLE
.Csv support

### ISSUE THREAD

**Issue by tnatna3131** [matigramirez/Parsec#56]
**First of all, hello, thank you for working for us.**

**I would love to see the csv format support all files. Of course, this is a difficult request, but it would be great if you could at least do this for sdata.**

**### Priority files;**

- NpcQuest.Sdata
- Cash.Sdata
- Guildhouse. Sdata
- KillStatus. Sdata

**The reason I wrote this is that the Csv file format can be easily edited via Excel.
Although the json file format can be read easily thanks to you, it is difficult for sdata files with a lot of content.**

**Thank you in advance for your future work.**

**Comment by matigramirez** [comment]
Files like `Item.SData`, `Monster.SData` and `Skill.SData` contain a list of simple records which can be represented in a table-like fashion, which is why the `csv` format is suitable in those cases.

`NpcQuest.SData` contains standard npcs, merchants, gatekeepers and quests, so, converting it to csv would take _at least_ 4 different `csv` files, which would then have to be re-combined into a single file again.
Sharing the `.SData` extension doesn't mean that all of them are serialized in the same way, it's merely a way for the game to know which files could be encrypted using KISA SEED (but that's a topic for a different conversation).

`json` is a suitable serialization format for non table-like formats, that's why it's the default supported serialization format in this library
